# : Manager [[[
[mgr]
cwd = { fg = "#e6e1e2" }

# Tab
tab_active = { fg = "#332e39", bg = "#ccc4d2", bold = true }
tab_inactive = { fg = "#e8dfee", bg = "#1e1a24" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#cabc85", bg = "#cabc85" }
marker_cut = { fg = "#e9e3cc", bg = "#e9e3cc" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#ccc7b1", bg = "#ccc7b1" }

# Count
count_copied = { fg = "#1e1c0e", bg = "#e9e3cc" }
count_cut = { fg = "#1e1c0e", bg = "#e9e3cc" }
count_selected = { fg = "#332e39", bg = "#ccc7b1" }

# Border
border_symbol = "│"
border_style  = { fg = "#ccc4d2" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#332e39", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ccc4d2", fg = "#332e39", bold = true }
normal_alt  = { bg = "#49464b", fg = "#cac5cb" }

# Select mode
select_main = { bg = "#cac5cb", fg = "#322f34", bold = true }
select_alt  = { bg = "#49464b", fg = "#cac5cb" }

# Unset mode
unset_main = { bg = "#ccc7b1", fg = "#333121", bold = true }
unset_alt  = { bg = "#49464b", fg = "#cac5cb" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#332e39", bg = "#ccc4d2" }
progress_error = { fg = "#690005", bg = "#ffb4ab" }

# Permissions
permissions_t = { fg = "#807582" }
permissions_w = { fg = "#8a815a" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#bba861" }
permissions_s = { fg = "#a07bb9" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ccc4d2" }
active = { fg = "#ccc7b1", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#ccc4d2" }
value = { fg = "#e6e1e2" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ccc4d2", bg = "#332e39" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ccc4d2" }
title = {}
hovered = { fg = "#e9e3cc", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3a393a" }
cand = { fg = "#ccc4d2" }
rest = { fg = "#332e39" }
desc = { fg = "#e6e1e2" }
separator = " ▶ "
separator_style = { fg = "#e6e1e2" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e6e1e2" }
run = { fg = "#e6e1e2" }
footer = { fg = "#322f34", bg = "#cac5cb" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#ccc7b1" }
title_warn = { fg = "#ccc4d2" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e6e1e2" },
    { name = "*/", fg = "#ccc4d2" },
]

# : ]]]
